#!/usr/bin/env bash

if ! [ -x "$(command -v protodoc)" ]
then
    echo "Please install coreos/protodoc first"
    echo "e.g) go get -v -u github.com/coreos/protodoc"
fi

TMPFILE=$(mktemp)
trap "{ rm -f ${TMPFILE}; }" EXIT

GOBGP=${GOPATH}/src/github.com/osrg/gobgp
DSTFILE=${GOBGP}/docs/sources/grpc_api.md

cd ${GOBGP}

protodoc \
    --directory=${GOBGP}/api \
    --title="gRPC API Reference" \
    --output=${TMPFILE}

echo '> This document is generated by [`protodoc.sh`](../../tools/docs/protodoc.sh).' >> ${TMPFILE}

cat -s ${TMPFILE} | sed 's/###/#/' | sed 's/###/##/' > ${DSTFILE}
